.mode csv
.import  export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
.import -skip 1 export1(1).csv temp
select count(email) from temp;